version: '3.8'

services:
  glogger:
    image: glogger
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "2112:2112"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - glogger
