apiVersion: v1
kind: Service
metadata:
  name: glogger
  namespace: monitoring
spec:
  selector:
    app: glogger
  type: NodePort
  ports:
  - name: grpc
    port: 8081
    targetPort: 8081
    nodePort: 30081
  - name: prometheus
    port: 2112
    targetPort: 2112